### ISSUE TITLE
[Bug]: Egg and Nest cannot be null!

### ISSUE THREAD

**Issue by ItzJustSamu** [FyreHost/FyreBot-issues#2]
### What happened?

on /createserver event the below log happens

3.0.6 Hotfix

### Version

1.0.3 (Edge)

### What setup are you seeing the bug on?

Pterodactyl (FyreBot Egg)

### Relevant log output

```shell
java.lang.IllegalArgumentException: Egg and Nest cannot be null!
        at com.mattmalec.pterodactyl4j.utils.Checks.notNull(Checks.java:31)
        at com.mattmalec.pterodactyl4j.application.entities.impl.CreateServerImpl.finalizeData(CreateServerImpl.java:226)
        at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.execute(PteroActionImpl.java:94)
        at com.mattmalec.pterodactyl4j.PteroAction.execute(PteroAction.java:97)
        at net.fyrehost.fyrebot.commands.CreateServerCommand.onCommand(CreateServerCommand.java:62)
        at net.fyrehost.fyrebot.Core.lambda$main$0(Core.java:99)
        at net.fyrehost.fyrebot.Core$$Lambda$718/0x000000007852acb0.apply(Unknown Source)
        at discord4j.core.event.EventDispatcher.lambda$on$1(EventDispatcher.java:125)
        at discord4j.core.event.EventDispatcher$$Lambda$736/0x00000000e80063b0.get(Unknown Source)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:125)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:311)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:992)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$DisposableWorkerTask.run(ForkJoinPoolScheduler.java:443)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker.processTaskQueue(ForkJoinPoolScheduler.java:407)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker$$Lambda$724/0x00000000784f5dc0.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrxbox98** [comment]
Fixed in 3.0.7
