### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Niclas-M1** [FyreHost/FyreBot-issues#7]
### Contact Details

Niclas_M#1302 (DC) ; niclasmueller1302@icloud,com

### What happened?

container@pterodactyl~ Server marked as starting...
[NarrowMining Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from fyrehost/yolks 
Status: Image is up to date for ghcr.io/fyrehost/yolks:java_8j9 
Digest: sha256:a36479f07dd64fe591de76d087af70dd43766a4eb3f0f4134fe724165b524a93 
[NarrowMining Daemon]: Finished pulling Docker container image
[FyreHost Dameon]: Contant us at support@fyrehost.net or on Discord for support.
container@pterodactyl~ java -Dterminal.jline=false -Dterminal.ansi=true -jar FyreBot.jar
╭─────────╮
│ FyreBot │
╰─────────╯
Loading...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Started Registrar
[15:7:14 INFO]: Global command: allow is up to date.
[15:7:14 INFO]: Global command: backup is up to date.
[15:7:14 INFO]: Global command: deny is up to date.
[15:7:14 INFO]: Global command: restart is up to date.
[15:7:14 INFO]: Global command: start is up to date.
[15:7:14 INFO]: Global command: restorebackup is up to date.
[15:7:14 INFO]: Global command: run is up to date.
[15:7:14 INFO]: Global command: createserver is up to date.
[15:7:14 INFO]: Global command: stopoutput is up to date.
[15:7:14 INFO]: Global command: graph is up to date.
[15:7:14 INFO]: Updated global command: manage
[15:7:14 INFO]: Global command: output is up to date.
[15:7:14 INFO]: Global command: help is up to date.
[15:7:14 INFO]: Global command: settoken is up to date.
[15:7:14 INFO]: Global command: nodes is up to date.
[15:7:14 INFO]: Global command: stop is up to date.
[15:7:14 INFO]: Global command: deleteserver is up to date.
[15:7:14 INFO]: Global command: deletebackup is up to date.
[15:7:14 INFO]: Global command: listbackups is up to date.
[15:7:14 INFO]: Global command: downloadbackup is up to date.
[15:7:14 INFO]: Global command: info is up to date.
[15:7:14 INFO]: Global command: status is up to date.
Finished Registrar
container@pterodactyl~ Server marked as running...
[15:7:14 INFO]: Loaded translation en-US
[15:7:14 INFO]: Started registering commands
[15:7:14 INFO]: Finished registering commands
com.mattmalec.pterodactyl4j.exceptions.ServerException: The server has encountered an Internal Server Error.
        at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.execute(PteroActionImpl.java:101)
        at com.mattmalec.pterodactyl4j.PteroAction.execute(PteroAction.java:97)
        at net.fyrehost.fyrebot.storage.Keys.addKey(Keys.java:37)
        at net.fyrehost.fyrebot.commands.SetTokenCommand.onCommand(SetTokenCommand.java:15)
        at net.fyrehost.fyrebot.commands.SetTokenCommand.onCommand(SetTokenCommand.java:11)
        at net.fyrehost.fyrebot.Core.lambda$main$0(Core.java:130)
        at net.fyrehost.fyrebot.Core$$Lambda$730/0x0000000020723860.apply(Unknown Source)
        at discord4j.core.event.EventDispatcher.lambda$on$1(EventDispatcher.java:125)
        at discord4j.core.event.EventDispatcher$$Lambda$749/0x0000000008010f90.get(Unknown Source)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:125)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:311)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:992)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$DisposableWorkerTask.run(ForkJoinPoolScheduler.java:443)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker.processTaskQueue(ForkJoinPoolScheduler.java:407)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker$$Lambda$736/0x00000000205651a0.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

### Version

1.0.2 (Default)

### What setup are you seeing the bug on?

Pterodactyl (FyreBot Egg)

### Relevant log output

```shell
container@pterodactyl~ Server marked as starting...
[NarrowMining Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from fyrehost/yolks 
Status: Image is up to date for ghcr.io/fyrehost/yolks:java_8j9 
Digest: sha256:a36479f07dd64fe591de76d087af70dd43766a4eb3f0f4134fe724165b524a93 
[NarrowMining Daemon]: Finished pulling Docker container image
[FyreHost Dameon]: Contant us at support@fyrehost.net or on Discord for support.
container@pterodactyl~ java -Dterminal.jline=false -Dterminal.ansi=true -jar FyreBot.jar
╭─────────╮
│ FyreBot │
╰─────────╯
Loading...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Started Registrar
[15:7:14 INFO]: Global command: allow is up to date.
[15:7:14 INFO]: Global command: backup is up to date.
[15:7:14 INFO]: Global command: deny is up to date.
[15:7:14 INFO]: Global command: restart is up to date.
[15:7:14 INFO]: Global command: start is up to date.
[15:7:14 INFO]: Global command: restorebackup is up to date.
[15:7:14 INFO]: Global command: run is up to date.
[15:7:14 INFO]: Global command: createserver is up to date.
[15:7:14 INFO]: Global command: stopoutput is up to date.
[15:7:14 INFO]: Global command: graph is up to date.
[15:7:14 INFO]: Updated global command: manage
[15:7:14 INFO]: Global command: output is up to date.
[15:7:14 INFO]: Global command: help is up to date.
[15:7:14 INFO]: Global command: settoken is up to date.
[15:7:14 INFO]: Global command: nodes is up to date.
[15:7:14 INFO]: Global command: stop is up to date.
[15:7:14 INFO]: Global command: deleteserver is up to date.
[15:7:14 INFO]: Global command: deletebackup is up to date.
[15:7:14 INFO]: Global command: listbackups is up to date.
[15:7:14 INFO]: Global command: downloadbackup is up to date.
[15:7:14 INFO]: Global command: info is up to date.
[15:7:14 INFO]: Global command: status is up to date.
Finished Registrar
container@pterodactyl~ Server marked as running...
[15:7:14 INFO]: Loaded translation en-US
[15:7:14 INFO]: Started registering commands
[15:7:14 INFO]: Finished registering commands
com.mattmalec.pterodactyl4j.exceptions.ServerException: The server has encountered an Internal Server Error.
        at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.execute(PteroActionImpl.java:101)
        at com.mattmalec.pterodactyl4j.PteroAction.execute(PteroAction.java:97)
        at net.fyrehost.fyrebot.storage.Keys.addKey(Keys.java:37)
        at net.fyrehost.fyrebot.commands.SetTokenCommand.onCommand(SetTokenCommand.java:15)
        at net.fyrehost.fyrebot.commands.SetTokenCommand.onCommand(SetTokenCommand.java:11)
        at net.fyrehost.fyrebot.Core.lambda$main$0(Core.java:130)
        at net.fyrehost.fyrebot.Core$$Lambda$730/0x0000000020723860.apply(Unknown Source)
        at discord4j.core.event.EventDispatcher.lambda$on$1(EventDispatcher.java:125)
        at discord4j.core.event.EventDispatcher$$Lambda$749/0x0000000008010f90.get(Unknown Source)
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:125)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:311)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:992)
        at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$DisposableWorkerTask.run(ForkJoinPoolScheduler.java:443)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker.processTaskQueue(ForkJoinPoolScheduler.java:407)
        at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker$$Lambda$736/0x00000000205651a0.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrxbox98** [comment]
It seems that the error is coming from the panel. When the bot checks the token, the panel is encountering an error.
